<?php
// module/Sermon/view/sermon/category/add.phtml:

$title = 'Edit category';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('category', array('action' => 'edit')));
$form->prepare();

echo $this->form()->openTag($form);

echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('title'));
echo $this->formRow($form->get('description'));
echo $this->formSubmit($form->get('submit'));
// echo $this->formCollection($form); // The above 4 lines can be replaced with this single line

echo $this->form()->closeTag();
