<?php
// module/Category/view/category/category/index.phtml:

$title = 'My categories';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('category', array('action'=>'add'));?>">Add new category</a>
</p>

<table class="table">
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($categories as $category) : ?>
<tr>
    <td><?php echo $this->escapeHtml($category->title);?></td>
    <td><?php echo $this->escapeHtml($category->description);?></td>
    <td>
        <a href="<?php echo $this->url('category',
            array('action'=>'edit', 'id' => $category->id));?>">Edit</a>
        <a href="<?php echo $this->url('category',
            array('action'=>'delete', 'id' => $category->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>
